generic-service:
  nameOverride: hmpps-ppud-automation-api
  productId: "HMPPS520" # productId for the product that this belongs to

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-ppud-automation-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-ppud-automation-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SPRING_DATA_REDIS_SSL_ENABLED: "true"
    CACHE_TIMETOLIVESECONDS: 43200  # 12 hours

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-ppud-automation-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      PPUD_USERNAME: "PPUD_USERNAME"
      PPUD_PASSWORD: "PPUD_PASSWORD"
    elasticache-redis:
      SPRING_DATA_REDIS_HOST: "primary_endpoint_address"
      SPRING_DATA_REDIS_PASSWORD: "auth_token"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-ppud-automation-api
