---
# Per environment values which override defaults in hmpps-ppud-automation-api/values.yaml

generic-service:
  ingress:
    host: hmpps-ppud-automation-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PPUD_URL: https://www.ppud.justice.gov.uk
    PPUD_RECALL_REVOCATIONISSUEDBYOWNER: "EO Recall(Recall Team)"
    PPUD_RECALL_RECALLTYPE: "To be determined"
    PPUD_RECALL_RETURNTOCUSTODYNOTIFICATIONMETHOD: "Already in custody"
    PPUD_OFFENDER_CASEWORKER_INCUSTODY: "Recall Reps Packs(Recall Team)"
    PPUD_OFFENDER_CASEWORKER_UAL: "Recall UAL checks(Recall Team)"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: make-recall-decision-prod
