---
# Per environment values which override defaults in hmpps-ppud-automation-api/values.yaml

generic-service:
  replicaCount: 8

  ingress:
    host: hmpps-ppud-automation-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    PPUD_URL: https://uat.ppud.justice.gov.uk
    DOCUMENT_MANAGEMENT_API_URL: https://document-api-preprod.hmpps.service.justice.gov.uk
    PPUD_RECALL_REVOCATIONISSUEDBYOWNER: "EO Recall(Recall Team)"
    PPUD_RECALL_RECALLTYPE_DETERMINATE: "To be determined"
    # TODO set PPUD_RECALL_RECALLTYPE_INDETERMINATE
    PPUD_RECALL_RETURNTOCUSTODYNOTIFICATIONMETHOD: "Already in custody"
    PPUD_OFFENDER_CASEWORKER_INCUSTODY: "Recall Reps Pack(Recall Team)"
    PPUD_OFFENDER_CASEWORKER_UAL: "Recall UAL checks(Recall Team)"
    ENVIRONMENT_NAME: preprod

  scheduledDowntime:
    enabled: true

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  # Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
  businessHoursOnly: true
  alertSeverity: make-recall-decision-nonprod
