---
# Per environment values which override defaults in hmpps-ppud-automation-api/values.yaml

generic-service:
  ingress:
    host: hmpps-ppud-automation-api.hmpps.service.justice.gov.uk

  env:
    PPUD_URL: https://www.ppud.justice.gov.uk
    PPUD_RECALL_REVOCATIONISSUEDBYOWNER: "EO Recall(Recall Team)"
    PPUD_RECALL_RECALLTYPE: "To be determined"
    PPUD_RECALL_RETURNTOCUSTODYNOTIFICATIONMETHOD: "Already in custody"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
